version: '2'
services:
  caddy:
    image: rothgar/rpi-caddy:0.9.1
    #build: caddy
    volumes:
      - "./.data/wp:/srv"
    depends_on:
      - mysql
      - php
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      rpi_net:
        ipv4_address: 172.19.0.4

  php:
    image: rothgar/rpi-php:5.6
    #build: php
    volumes:
      - "./.data/wp:/srv"
    restart: always
    networks:
      rpi_net:
        ipv4_address: 172.19.0.5
    
  mysql:
    image: rothgar/rpi-mysql:5.5
    #build: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.data/backup/1n7:/docker-entrypoint-initdb.d"
    restart: always
    env_file:
      env_mysql.env
    networks:
      rpi_net:
        ipv4_address: 172.19.0.6

networks:
   rpi_net:
     driver: bridge
     driver_opts:
       com.docker.network.enable_ipv6: "false"
       com.docker.network.bridge.enable_ip_masquerade: "true"
     ipam:

       driver: default
       config:
         - subnet: 172.19.0.0/16
           gateway: 172.19.0.1
         
# Use these images for dynamic DDNS updates
# For Google domains use http://j.mp/2bRNYET
# Make sure you update WWW and @ DNS entries
#
#  inadyn:
#    image: rothgar/rpi-inadyn:1.99.15
#    environment:
#      SYSTEM: default@domains.google.com
#      USERNAME: UUUUU
#      PASSWORD: PPPPP
#      ALIAS: example.com
#
#  inadyn_www:
#    image: rothgar/rpi-inadyn:1.99.15
#    environment:
#      SYSTEM: default@domains.google.com
#      USERNAME: UUUUU
#      PASSWORD: PPPPP
#      ALIAS: www.example.com
